export const CgoIcon: any;
export const CgoButton: any;
export const CgoBadge: any;
export const CgoInput: any;
export const CgoCard: any;
export const CgoTable: any;
export const CgoMediaViewer: any;
export const CgoFloatingWindow: any;
export const CgoAdminSelect: any;
export const CgoPreferenceItem: any;
export const CgoLineBadge: any;
export const CgoLevelCard: any;
export const CgoSpinner: any;
export const CgoToast: any;
export const CgoTooltip: any;
export const CgoDropdown: any;
export const CgoModal: any;
export const CgoTabs: any;
export const CgoTab: any;
export const CgoAvatar: any;
export const CgoChatBubble: any;
export const CgoCaptcha: any;
export const CgoThemeToggle: any;
export const CgoSideNav: any;
export const CgoNavItem: any;
export const CgoToolbarSelect: any;
export const CgoNoticeCard: any;
export const CgoNoticeCenter: any;
export const CgoNoticePopup: any;
export const showToast: (...args: any[]) => any;
export const showNoticePopup: (...args: any[]) => any;
export const generateCaptcha: (...args: any[]) => any;
export const ICONS: Record<string, any>;
export const buildSvg: (...args: any[]) => string;
export const iconNames: () => string[];
export * as theme from './theme.js';
